services:
  auth-center:
    image: auth-center:python-3.11
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-center
    restart: unless-stopped

    ports:
      - "8000:8000"
    volumes:
      - ./app:/app

    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

    depends_on:
      - auth-center-redis
    networks:
      - agent-net
      - auth-center-net

  auth-center-redis:
    image: redis:8.4.0-alpine3.22
    container_name: auth-center-redis
    restart: unless-stopped
    networks:
      - auth-center-net


networks:
  agent-net:
    external: true
  auth-center-net:
    driver: bridge
